
# 站点关键字
keywords: "Secret Blog"

# 建站日期
since: 2016

# 导航栏
menu:
  首页: /
  关于: /about
  友链: /links

# 联系方式
social:
  QQ:
  邮箱:
  微博:
  GitHub:
  Coding:

# 底部字数统计，需安装 hexo-wordcount 插件
# 安装命令 npm install hexo-wordcount，然后启用为 enabled
footer_wordcount: disabled

# 底部版权补充
footer_expand: 'Hosted by <a href="https://pages.coding.me">Coding Pages</a>, '

# 站点微缩图
favicon: /favicon.ico

# 站点 Logo
logo: /favicon.png

# 一言 hitokoto
hitokoto: enabled

# Gitment
gitment:
  owner:
  repo:
  client_id:
  client_secret:

# 腾讯统计
tencent_analytics:

# CSS 样式表路径
stylesheets:
- //fonts.openapi.link/css?family=Lato:300,300italic,400,400italic,700,700italic&amp;subset=latin,latin-ext
- /css/font-awesome.min.css
- /css/gitment.css
- /css/hola.css

# Javascript 脚本路径
scripts:
- /js/jquery.min.js
- /js/fetch.min.js
- /js/instantclick.min.js
- /js/gitment.browser.min.js
- /js/hola.js
